# Generated by Django 5.2.1 on 2025-05-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('student_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Prefer not to say')], max_length=10)),
                ('dob', models.DateField()),
                ('course', models.CharField(choices=[('BSAIS', 'BS in Accounting and Information System'), ('BSCS', 'BS in Computer Science'), ('BSHM', 'BS in Hospitality Management'), ('BSIT', 'BS in Information Technology'), ('BSTM', 'BS in Tourism Management')], max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
    ]
