# Generated by Django 5.2.1 on 2025-05-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurApp', '0002_alter_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(choices=[('BSAIS', 'BS in Accounting and Information System'), ('BSCS', 'BS in Computer Science'), ('BSHM', 'BS in Hospitality Management'), ('BSIT', 'BS in Information Technology'), ('BSTM', 'BS in Tourism Management')], max_length=100, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fname',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Prefer not to say')], max_length=50, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lname',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
    ]
