# Generated by Django 5.2.1 on 2025-05-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurApp', '0003_remove_userprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Prefer not to say')], max_length=10, verbose_name='Gender'),
        ),
    ]
