# Generated by Django 5.2.1 on 2025-05-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurApp', '0006_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Female', 'F'), ('Male', 'M'), ('Prefer not to say', 'P')], max_length=100, verbose_name='Gender'),
        ),
    ]
